# Generated by Django 4.2.9 on 2024-01-26 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('data', 'Data File'), ('lapse', 'Lapse File'), ('experience', 'Experience File')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LapseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, null=True)),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='app.filemodel')),
                ('experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='app.filemodel')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='app.filemodel')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='app.filemodel')),
            ],
        ),
    ]
