# Generated by Django 4.2.9 on 2024-01-26 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_lapseanalysis_experience_lapseanalysis_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapseanalysis',
            name='end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end', to='app.filemodel'),
        ),
        migrations.AlterField(
            model_name='lapseanalysis',
            name='output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output', to='app.filemodel'),
        ),
        migrations.AlterField(
            model_name='lapseanalysis',
            name='rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate', to='app.filemodel'),
        ),
        migrations.AlterField(
            model_name='lapseanalysis',
            name='start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start', to='app.filemodel'),
        ),
    ]
