# Generated by Django 4.2.9 on 2024-02-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lapseanalysis_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lapseanalysis',
            name='epochs',
            field=models.IntegerField(default=50),
        ),
    ]
