# Generated by Django 4.2.9 on 2024-02-02 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_lapseanalysis_projection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='type',
            field=models.CharField(blank=True, choices=[('data', 'Data File'), ('lapse', 'Lapse File'), ('rate', 'Rate File'), ('assumption', 'Assumption File'), ('projection', 'Projection File')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_lapse_analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.lapseanalysis')),
            ],
        ),
    ]
