# Generated by Django 4.2.9 on 2024-03-29 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_joint_file_alter_filemodel_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Joint',
            new_name='Join',
        ),
    ]
