# Generated by Django 4.2.9 on 2024-03-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
