# Generated by Django 4.2.9 on 2024-03-29 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_join_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='rate_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_file', to='app.filemodel'),
        ),
    ]
