# Generated by Django 4.2.9 on 2024-03-29 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_period_rate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapseanalysis',
            name='assumption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assumption_2', to='app.filemodel'),
        ),
        migrations.CreateModel(
            name='DNN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('model', models.CharField(max_length=512, null=True)),
                ('epochs', models.IntegerField(default=50)),
                ('assumption_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assumption', to='app.filemodel')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period', to='app.period')),
            ],
        ),
    ]
