# Generated by Django 4.2.9 on 2024-03-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_projection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lapseanalysis',
            name='assumption',
        ),
        migrations.RemoveField(
            model_name='lapseanalysis',
            name='data',
        ),
        migrations.RemoveField(
            model_name='lapseanalysis',
            name='end',
        ),
        migrations.RemoveField(
            model_name='lapseanalysis',
            name='projection',
        ),
        migrations.RemoveField(
            model_name='lapseanalysis',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='lapseanalysis',
            name='start',
        ),
        migrations.AlterField(
            model_name='projection',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.DeleteModel(
            name='General',
        ),
        migrations.DeleteModel(
            name='LapseAnalysis',
        ),
    ]
