# Generated by Django 4.2.9 on 2024-04-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
