# Generated by Django 4.2.9 on 2024-04-03 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_proj_ind'),
    ]

    operations = [
        migrations.AddField(
            model_name='proj_ind',
            name='file_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proj_ind_end', to='app.filemodel'),
        ),
        migrations.AddField(
            model_name='proj_ind',
            name='file_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proj_ind_start', to='app.filemodel'),
        ),
    ]
